name: Basic workflow

# Trigger
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Target environment

jobs:
  job1:
    name: Job 1
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment name
        run: echo ${{ inputs.environment }}
